<?php

/* 
* Generated by the form builder
*/

?>
<?php echo $this->form->open(); ?>

    <?php foreach ($this->form->fields as $field): ?>

        <div class="form-group<?php echo isset($field['error']) ? ' has-error has-feedback' : ''; ?>">

        <?php

        // Check if we need to add the form-control class
        if (in_array($field['type'], array('text', 'password', 'textarea', 'dropdown', 'upload')))
        {
            if (isset($field['attributes']['class']))
            {
                $field['attributes']['class'] = 'form-control ' . $field['attributes']['class'];
            }
            else
            {
                $field['attributes']['class'] = 'form-control';
            }
        }

        if (isset($field['label']) && ! in_array($field['type'], array('checkbox')))
        {
            echo $this->form->label($field['label'], $field['name'], array('class' => 'control-label'));

            // Add an ID attribute to the input if we have a label
            if ( ! isset($field['attributes']['id']))
            {
                $field['attributes']['id'] = $field['name'];
            }
        }

        if ($field['type'] === 'text')
        {
            echo $this->form->text($field['name'], $field['data'], $field['attributes']);
        }
        else if ($field['type'] === 'password')
        {
            echo $this->form->password($field['name'], $field['attributes']);
        }
        else if ($field['type'] === 'textarea')
        {
            echo $this->form->textarea($field['name'], $field['data'], $field['attributes']);
        }
        else if ($field['type'] === 'hidden')
        {

        }
        else if ($field['type'] === 'upload')
        {
            
        }
        else if ($field['type'] === 'dropdown')
        {
            echo $this->form->dropdown($field['name'], $field['options'], $field['data'], $field['attributes']);
        }
        else if ($field['type'] === 'radio')
        {
            
        }

        ?>

        <?php if ($field['type'] === 'checkbox'): ?>

            <div class="checkbox">
                <label>
                    <?php echo $this->form->checkbox($field['name'], $field['value'], $field['data']); ?> <?php echo $field['label']; ?>
                </label>
            </div>

        <?php endif; ?>

        <?php if (isset($field['error'])): ?>
            <span class="fa fa-times form-control-feedback"></span>
            <p class="help-block"><?php echo $field['error']; ?></p>
        <?php endif ?>

        </div>

    <?php endforeach; ?>

    <button type="submit" class="btn btn-success"><?php echo $this->form->button; ?></button>

<?php echo $this->form->close(); ?>